version: 1
formatters:
  hiformat:
    format: '[%(name)s][%(levelname)1.8s][%(asctime)s][%(module)s:%(lineno)d] %(message)s'
  simple:
    format: '[%(name)s][%(levelname)1.8s][%(asctime)s] %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: hiformat
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: simple
    filename: logs/itinfo-api.log
loggers:
  console:
    level: DEBUG
    handlers: [console]
    propagate: no
  file:
    level: DEBUG
    handlers: [file]
    propagate: no
root:
  level: DEBUG
  handlers: [console,file]