"""empty message

Revision ID: 0643f78085b3
Revises: 1a6889cdcb27
Create Date: 2019-01-16 01:59:43.633512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0643f78085b3'
down_revision = '1a6889cdcb27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servers', sa.Column('backup', sa.Boolean(), nullable=True))
    op.add_column('servers', sa.Column('prod_server', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servers', 'prod_server')
    op.drop_column('servers', 'backup')
    # ### end Alembic commands ###
