"""empty message

Revision ID: 4fcc462e9761
Revises: a72c0339c94b
Create Date: 2019-01-16 02:27:39.225937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fcc462e9761'
down_revision = 'a72c0339c94b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servers', sa.Column('ip', sa.String(length=15), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servers', 'ip')
    # ### end Alembic commands ###
