"""empty message

Revision ID: 75843e47b1d6
Revises: 4fcc462e9761
Create Date: 2019-01-16 02:38:16.228977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75843e47b1d6'
down_revision = '4fcc462e9761'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servers', sa.Column('ip_zone', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servers', 'ip_zone')
    # ### end Alembic commands ###
